---
# https://docs.docker.com/engine/installation/linux/centos/#install-from-a-package
# https://download.docker.com/linux/centos/<centos_version>>/x86_64/stable/Packages/
# or do 'yum --showduplicates list docker-engine'
docker_versioned_pkg:
  'latest': docker-ce
  '19.03': docker-ce-19.03.14-3.el{{ ansible_distribution_major_version }}
  '20.10': docker-ce-20.10.5-3.el{{ ansible_distribution_major_version }}
  'stable': docker-ce-19.03.14-3.el{{ ansible_distribution_major_version }}
  'edge': docker-ce-19.03.14-3.el{{ ansible_distribution_major_version }}

docker_cli_versioned_pkg:
  'latest': docker-ce-cli
  '19.03': docker-ce-cli-19.03.14-3.el{{ ansible_distribution_major_version }}
  '20.10': docker-ce-cli-20.10.5-3.el{{ ansible_distribution_major_version }}

containerd_versioned_pkg:
  'latest': containerd.io
  '1.2.13': containerd.io-1.2.13-3.2.el7
  '1.3.7': containerd.io-1.3.7-3.1.el{{ ansible_distribution_major_version }}
  '1.3.9': containerd.io-1.3.9-3.1.el{{ ansible_distribution_major_version }}
  '1.4.4': containerd.io-1.4.4-3.1.el{{ ansible_distribution_major_version }}
  'stable': containerd.io-1.3.9-3.1.el{{ ansible_distribution_major_version }}
  'edge': containerd.io-1.3.9-3.1.el{{ ansible_distribution_major_version }}

docker_package_info:
  enablerepo: "docker-ce"
  pkgs:
    - "{{ containerd_versioned_pkg[containerd_version | string] }}"
    - "{{ docker_cli_versioned_pkg[docker_cli_version | string] }}"
    - "{{ docker_versioned_pkg[docker_version | string] }}"
